apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: mlflow
      context: .
      docker:
        dockerfile: Dockerfile 
deploy:
  kubectl:
    manifests:
      - k8s/postgres.yaml
      - k8s/mlflow.yaml
profiles:
  - name: minikube
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: k8s/minikube.yaml
