apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: ./postgres-db-pv
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: k8s.io/minikube-hostpath
