apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      initContainers:
      - name: mlflow-db-upgrade
        image: mlflow
        command: 
        - "bash"
        - "-c"
        - "date"
        #- >-
        #  mlflow db upgrade postgresql://mlflow:mlflow@postgres:5432/mlflow      
      containers:
      - name: mlflow
        image: mlflow
        command: 
        - "bash"
        - "-c"
        - >-
          mlflow server
          --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
          --default-artifact-root /mlruns
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2048Mi"
        volumeMounts:
          - name: mlflow-artifact-volume
            mountPath: /mlruns
      volumes:
        - name: mlflow-artifact-volume
          persistentVolumeClaim:
            claimName: mlflow-artifact-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: mlflow
spec:
  ports:
  - port: 5000
  selector:
    app: mlflow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifact-pvc
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
